### ISSUE TITLE
Panic in ChannelStats

### ISSUE THREAD

**Issue by 0x46616c6b** [lovoo/nsq_exporter#9]
```
goroutine 51 [running]:
panic(0x80c8a0, 0xc820010050)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/lovoo/nsq_exporter/collector.ChannelStats.func6(0xc820206090, 0xc820294cf0)
        /go/src/github.com/lovoo/nsq_exporter/collector/stats_channel.go:62 +0x99
github.com/lovoo/nsq_exporter/collector.channelStats.collect(0xc8200a7400, 0xa, 0xa, 0xc820216018, 0xc82000cba0)
        /go/src/github.com/lovoo/nsq_exporter/collector/stats_channel.go:115 +0x3cf
github.com/lovoo/nsq_exporter/collector.(*channelStats).collect(0xc820108920, 0xc820216018, 0xc82000cba0)
        <autogenerated>:3 +0xb5
github.com/lovoo/nsq_exporter/collector.(*NsqdStats).Collect.func1(0xc820216018, 0xc82000cba0, 0xc8202912e0, 0x7f754ac27a10, 0xc820108920)
        /go/src/github.com/lovoo/nsq_exporter/collector/nsqd.go:54 +0x3b
created by github.com/lovoo/nsq_exporter/collector.(*NsqdStats).Collect
        /go/src/github.com/lovoo/nsq_exporter/collector/nsqd.go:56 +0x184
2016/08/09 07:19:08 listening to :9117
panic: runtime error: index out of range
```

**Comment by 0x46616c6b** [comment]
Fixed in #8
